### ISSUE TITLE
Use balanced_tree=False for cKDTree

### ISSUE THREAD

**Issue by ahartikainen** [fatiando/verde#146]
**Description of the desired feature**

For large number of points, tree construction is slow if the default is used: `balanced_tree=True`. All of this is assuming that points are "more or less" random order, meaning that order of points is not sorted in 3D.

https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.cKDTree.html

This could be implemented with either lambda

    from scipy.spatial import cKDTree # pylint: disable=no-name-in-module
    KDTree = lambda x: cKDTree(x, balanced_tree=False)

or partial

    from functools import partial
    from scipy.spatial import cKDTree # pylint: disable=no-name-in-module
    KDTree = partial(cKDTree, balanced_tree=False)

**Are you willing to help implement and maintain this feature?** Yes/No

Maybe

**Comment by leouieda** [comment]
Hi Ari, thanks for the suggestion! In `BlockReduce`, we form a tree with points that are on a regular grid and then query the actual scattered points. Do you think that using `balanced_tree=False` might speed things up in this case? We should probably do a benchmark to try this out (maybe using the bathymetry or magnetic data, which are the largest we have).

Installing `pykdtree` already gives a huge speed boost but it doesn't have the `balanced_tree` option.
