### ISSUE TITLE
Return an array from cross_val_score

### ISSUE THREAD

**Issue by leouieda** [fatiando/verde#155]
Function `verde.model_selection.cross_val_score` fits gridders to many folds of the data and calculates the score for each fold. It currently returns a list of the scores, which is annoying if want to calculate the mean score. For example  `cross_val_score(...).mean()` doesn't work and needs to be `np.mean(cross_val_score(...))`. So it would be better if `cross_val_score` returned a numpy array instead.

**Comment by Goto15** [comment]
Would you mind if I took this issue? 

I have a few thoughts on how to solve this that I would like to try out.

**Comment by leouieda** [comment]
@Goto15 go ahead! Thank you for volunteering 🎉🎉

Please take a look at our [Contributing guide](https://github.com/fatiando/verde/blob/master/CONTRIBUTING.md) for standards and instructions.

**Comment by Goto15** [comment]
So the solution I came to is to simply cast the result as a numpy array. 

This will work with mean(). However, if the results need to be mutable this could cause issues. Currently my code passes all tests, but I wanted to double check that this would be a desired solution before I submitted a PR.

**Comment by leouieda** [comment]
That is exactly what I had in mind! Please feel free to open a PR with that 👍 Thanks!
