### ISSUE TITLE
Tutorial for grid generation and coordinates

### ISSUE THREAD

**Issue by leouieda** [fatiando/verde#161]
**Description of the desired feature**

We need a tutorial about generating regular grids and all the details surrounding how the coordinates are determined (spacing, adjustments, registration, etc). This would one of the very first tutorials and would help explain some of the concepts in the `grid_coordinates` docstring in more detail.

**Comment by jessepisel** [comment]
I'm thinking of taking a crack at doing some documentation in June. I think this would be a fun place to start with a tutorial that incorporates #164 in as well. @leouieda What do you think? Also, do you have any particular verde dataset in mind?

**Comment by leouieda** [comment]
@jessepisel that would be great! All help is much appreciated :)  No dataset in mind. Actually, this one probably doesn't need a dataset since it won't be gridding anything. It's more about the details of how we handle grid coordinates generation (spacing vs shape, adjusting spacing vs region, pixel registration, etc). If needed, I think `verde.datasets.CheckerBoard` should do nicely.

Not sure if #164 fits here, though. It might be better to have another page with the "Basics of Interpolation" or something like that.

**Comment by jessepisel** [comment]
That sounds good to me. I will go through and make a tutorial for grid generation and leave #164 for later on this month. I'll put in a PR when I have something this upcoming week.
