### ISSUE TITLE
Add implementation for geographic coordinates conversion

### ISSUE THREAD

**Issue by santisoler** [fatiando/verde#172]
**Description of the desired feature**

The geographic coordinates conversion have been implemented on Harmonica.
I don't remember exactly why we added the functions there and not on Verde.
Would it be Verde a better place for them?

**Comment by leouieda** [comment]
The geographic -> geocentric spherical conversion relies on the ellipsoid parameters, which is in Harmonica for normal gravity. We could do that here and ask for pyproj or cartopy ellipsoids but I'm not sure how well that would work.

**Comment by santisoler** [comment]
I don't think having repeated code would be a good choice. Giving second thoughts to this issue, I realize that even the geographic -> geocentric spherical conversion is a mere geometry operation on coordinates, it rarely would be used in Verde.

@leouieda if you agree we could close this issue.

**Comment by ahartikainen** [comment]
Is there a possibilty to use geographical coordinates in cKDTree calculations for distance?

Pyproj has implemented these.

**Comment by djhoese** [comment]
@ahartikainen Do you have a link to these calculations? In the `pyresample` project we've always converted lon/lats to xyz coordinates before putting them in a kdtree.

**Comment by ahartikainen** [comment]
Sorry, I meant that distance calculations can be done with pyproj, but I'm not sure how we could use those in KDTree structure.

**Comment by leouieda** [comment]
@ahartikainen not that I'm aware. I wondered if we could use great circle distances but it seems like there is no easy way to plug a custom distance function.

**Comment by leouieda** [comment]
> @leouieda if you agree we could close this issue.

I agree. This is common in global gravity using tesseroids but probably not much else.
