### ISSUE TITLE
AttributeError: module 'cartopy.feature' has no attribute 'STATES'

### ISSUE THREAD

**Issue by AminoACID123** [fatiando/verde#199]
**Description of the problem**

**Full code that generated the error**

```
 def _setup_map(
        ax, xticks, yticks, crs, region, land=None, ocean=None, borders=None, states=None
    ):
        """
        Setup a Cartopy map with land and ocean features and proper tick labels.
        """
        import cartopy.feature as cfeature
        from cartopy.mpl.ticker import LongitudeFormatter, LatitudeFormatter
    
        if land is not None:
            ax.add_feature(cfeature.LAND, facecolor=land)
        if ocean is not None:
            ax.add_feature(cfeature.OCEAN, facecolor=ocean)
        if borders is not None:
            ax.add_feature(cfeature.BORDERS, linewidth=borders)
        if states is not None:
>           ax.add_feature(cfeature.STATES, linewidth=states)
```

**Full error message**

```
AttributeError: module 'cartopy.feature' has no attribute 'STATES'

verde/datasets/sample_data.py:39: AttributeError

```

**System information**

* Operating system: ubuntu18.04
* Python installation (Anaconda, system, ETS):python3.6
* Version of Python:3.6
* Version of this package:1.1.0
* If using conda, paste the output of `conda list` below:

<details>
<summary>output of conda list</summary>
<pre>
PASTE OUTPUT OF CONDA LIST HERE
</pre>
</details>

**Comment by leouieda** [comment]
Hi @AminoACID123, could you please post the output of `pip freeze`? This is a problem with your cartopy install, not Verde itself.

**Comment by leouieda** [comment]
Closing since this is probably not related to Verde and haven't gotten a response.
