### ISSUE TITLE
AGU2019 abstract

### ISSUE THREAD

**Issue by leouieda** [fatiando/verde#200]
Hey @santisoler @jessepisel I'm thinking of submitting an abstract about Verde to one of the software sessions at AGU. Sorry for the short notice. I was thinking of not submitting but changed my mind :) **Would you two be interested in being co-authors?** You've both been helping quite a bit. 

I'll get started on the abstract tonight so please let me know as soon as you can (deadline is wednesday).

**Comment by jessepisel** [comment]
I’m definitely down. What can I do to help?

**Comment by leouieda** [comment]
Gotta think a bit, actually. I might have to submit something on PyGMT as well. But for now it would be mostly looking over the abstract and making sure it's good :)

**Comment by santisoler** [comment]
I'll be glad to coauthor it! Let us know if you need any help.

**Comment by leouieda** [comment]
Sorry Jesse and Santi. I ended submitting a PyGMT abstract. Gotta pay the bills.
