### ISSUE TITLE
Remove VectorSpline2D

### ISSUE THREAD

**Issue by leouieda** [fatiando/verde#205]
Verde has the `verde.VectorSpline2D` which is a joint interpolation of 2D vectors tied through elasticity. This actually doesn't make much sense for most data types and was originally designed for GPS data. Since Verde is supposed to be general purpose, this class feels like it doesn't belong here. My thought is to move it to a separate library just for GPS interpolation. 

The transition would involve:

1. Include a deprecation warning for `VectorSpline2D` saying that it will be removed in 
Verde 2.0.0 (since it breaks backward compatibility). It should point to the new home of the class (which we don't yet have).
2. Make a release that included the warning (1.3.0 probably)
3. Remove the class from the Verde 2.0 branch

Any thoughts or help on this are welcome!

**Comment by leouieda** [comment]
This is actually a good home for this class: https://github.com/fatiando/erizo

**Comment by jessepisel** [comment]
I think that's a good idea to move it to the new library and deprecate it as you suggested. This gives those using it some time to prepare for the move and deprecation. The new library looks great. Let me know how I can help with this.

**Comment by leouieda** [comment]
:+1: thanks @jessepisel! Right now, we need to move the relevant tutorial pages to Erizo:

* An overview of the package, similar to Verde's `tutorials/overview.py` but focused on the coupled interpolation.
* Move relevant tutorial sections from Verde. Mainly `tutorials/vector.py` but without the decoupled version of the interpolation. 

In Verde, we should add the deprecation warning and remove the gallery example and tutorial section (maybe replace the section with a warning to move to Erizo instead). We can make a 0.1.0 release of Erizo soon so people won't be left without the class just in case.
