### ISSUE TITLE
Azure Pipeline Warning

### ISSUE THREAD

**Issue by jessepisel** [fatiando/verde#232]
On the Azure pipeline Mac Python38 check there is the following warning:
```
##[warning]This pipeline uses a Microsoft-hosted agent image that will be removed on March 23, 2020 (MacOS-10.13). You must make changes to your pipeline before that date, or else your pipeline will fail. Learn more (https://aka.ms/removing-older-images-hosted-pools).
```

Looks like we need to update it to MacOS-10.14 or MacOS-10.15 (Catalina) on Azure. Is there any preference on which one we migrate to?

**Comment by leouieda** [comment]
Thanks for catching that @jessepisel! It seems like it's just a matter of changing this line: https://github.com/fatiando/verde/blob/master/.azure-pipelines.yml#L74

I would say go for the latest so we don't have to do this again so soon :slightly_smiling_face:

**Comment by jessepisel** [comment]
Thanks for showing me where that is located, I would have flailed for a while looking for it. I changed it and everything built without warning on 10.15 in #234 so it should be good to go for a few update cycles :thumbsup:
