### ISSUE TITLE
Problems with Cartopy plots for v0.18

### ISSUE THREAD

**Issue by leouieda** [fatiando/verde#269]
Something happened in Cartopy and now our plots aren't working with the coast line features:

![sphx_glr_blockkfold_001](https://user-images.githubusercontent.com/290082/83788380-03a58480-a68d-11ea-9ec5-e11234303786.png)

Will quickly pin the version on CI used to make our docs to 0.17.* but we should investigate to see if it's a bug on our end.

**Comment by santisoler** [comment]
We should keep track of https://github.com/SciTools/cartopy/issues/1578 for any update. I think we are experiencing the same problem.

**Comment by leouieda** [comment]
Closing since we now require Cartopy >=0.18 for the docs builds.
