### ISSUE TITLE
appdirs module not found

### ISSUE THREAD

**Issue by jessepisel** [fatiando/verde#286]
**Description of the problem**
Just added a new install of `verde` to Python 3.7.3 and it will not import `verde`. It looks like the error is coming out of `pooch` where it is looking for `appdirs`, I didn't see this issue over there so I am not sure what might be happening

**Full code that generated the error**

```python
import verde as vd
```

**Full error message**

```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-48-121102e56c35> in <module>
      3 import pandas as pd
      4 import geostatspy.geostats as geostats
----> 5 import verde as vd
      6 get_ipython().run_line_magic('matplotlib', 'inline')

~\AppData\Local\Continuum\anaconda3\lib\site-packages\verde\__init__.py in <module>
      1 # pylint: disable=missing-docstring,import-outside-toplevel
      2 # Import functions/classes to make the public API
----> 3 from . import datasets
      4 from . import version
      5 from .coordinates import (

~\AppData\Local\Continuum\anaconda3\lib\site-packages\verde\datasets\__init__.py in <module>
      1 # pylint: disable=missing-docstring
      2 from .synthetic import CheckerBoard
----> 3 from .sample_data import (
      4     locate,
      5     fetch_baja_bathymetry,

~\AppData\Local\Continuum\anaconda3\lib\site-packages\verde\datasets\sample_data.py in <module>
      7 import numpy as np
      8 import pandas as pd
----> 9 import pooch
     10 
     11 try:

~\AppData\Local\Continuum\anaconda3\lib\site-packages\pooch\__init__.py in <module>
      2 # Import functions/classes to make the API
      3 from . import version
----> 4 from .core import Pooch, create, retrieve
      5 from .utils import os_cache, file_hash, make_registry, check_version, get_logger
      6 from .downloaders import HTTPDownloader, FTPDownloader, SFTPDownloader

~\AppData\Local\Continuum\anaconda3\lib\site-packages\pooch\core.py in <module>
      9 
     10 import requests
---> 11 from .utils import (
     12     check_version,
     13     parse_url,

~\AppData\Local\Continuum\anaconda3\lib\site-packages\pooch\utils.py in <module>
     10 from contextlib import contextmanager
     11 
---> 12 import appdirs
     13 from packaging.version import Version
     14 

ModuleNotFoundError: No module named 'appdirs'
```

**System information**

* Operating system: Windows 10
* Python installation (Anaconda, system, ETS): Anaconda
* Version of Python: 3.7.3
* Version of this package: 1.5.0 and 0.7.0 for pooch
* If using conda, paste the output of `conda list` below:

<details>
<summary>output of conda list</summary>
<pre>
# Name                    Version                   Build  Channel
_anaconda_depends         2019.03                  py37_0  
_ipyw_jlab_nb_ext_conf    0.1.0                    py37_0  
alabaster                 0.7.12                   py37_0  
anaconda                  custom                   py37_1  
anaconda-client           1.7.2                    py37_0  
anaconda-navigator        1.9.12                   py37_0  
anaconda-project          0.8.4                      py_0  
appdirs                   1.4.3                    pypi_0    pypi
argon2-cffi               20.1.0           py37he774522_1  
arrow                     0.15.5                   pypi_0    pypi
asn1crypto                1.4.0                      py_0  
astroid                   2.4.2                    py37_0  
astropy                   4.0.1.post1      py37he774522_1  
atomicwrites              1.4.0                      py_0  
attrs                     20.1.0                     py_0  
babel                     2.8.0                      py_0  
backcall                  0.2.0                      py_0  
backports                 1.0                        py_2  
backports.functools_lru_cache 1.6.1                      py_0  
backports.os              0.1.1                 py37_1002  
backports.shutil_get_terminal_size 1.0.0                    py37_2  
backports.tempfile        1.0                        py_1  
backports.weakref         1.0.post1                  py_1  
beautifulsoup4            4.9.1                    py37_0  
binaryornot               0.4.4                    pypi_0    pypi
bitarray                  1.5.3            py37he774522_0  
bkcharts                  0.2                      py37_0  
black                     18.9b0                   pypi_0    pypi
black-nb                  0.2.3                    pypi_0    pypi
blas                      1.0                         mkl  
bleach                    3.1.5                      py_0  
blosc                     1.20.0               h7bd577a_0  
bokeh                     1.3.4                    pypi_0    pypi
boto                      2.49.0                   py37_0  
bottleneck                1.3.2            py37h2a96729_1  
branca                    0.4.1                    pypi_0    pypi
brotlipy                  0.7.0           py37he774522_1000  
bzip2                     1.0.8                he774522_0  
ca-certificates           2020.7.22                     0  
certifi                   2020.6.20                py37_0  
cffi                      1.14.2           py37h7a1dbc1_0  
chardet                   3.0.4                 py37_1003  
click                     7.1.2                      py_0  
cloudpickle               1.6.0                      py_0  
clyent                    1.2.2                    py37_1  
colorama                  0.4.3                      py_0  
colour                    0.1.5                    pypi_0    pypi
comtypes                  1.1.7                 py37_1001  
conda                     4.8.4                    py37_0  
conda-build               3.18.8                   py37_0  
conda-env                 2.6.0                         1  
conda-package-handling    1.6.1            py37h62dcd97_0  
conda-verify              3.4.2                      py_1  
console_shortcut          0.1.1                         3  
contextlib2               0.6.0.post1                py_0  
cookiecutter              1.7.0                    pypi_0    pypi
cryptography              3.1              py37h7a1dbc1_0  
curl                      7.71.1               h2a8f88b_1  
cycler                    0.10.0                   py37_0  
cython                    0.29.21          py37ha925a31_0  
cytoolz                   0.10.1           py37he774522_0  
dask                      2.25.0                     py_0  
dask-core                 2.25.0                     py_0  
decorator                 4.4.2                      py_0  
defusedxml                0.6.0                      py_0  
dill                      0.3.2                      py_0  
distributed               2.25.0                   py37_0  
docutils                  0.16                     py37_1  
dtreeviz                  0.7.1                    pypi_0    pypi
entrypoints               0.3                      py37_0  
espatools                 0.0.8                    pypi_0    pypi
et_xmlfile                1.0.1                   py_1001  
fast-histogram            0.9              py37h2a96729_0  
fastcache                 1.1.0            py37he774522_0  
filelock                  3.0.12                     py_0  
flask                     1.1.2                      py_0  
freetype                  2.10.2               hd328e21_0  
fsspec                    0.8.0                      py_0  
future                    0.18.2                   py37_1  
geographiclib             1.50                     pypi_0    pypi
geopy                     2.0.0                    pypi_0    pypi
geostatspy                0.0.19                   pypi_0    pypi
get_terminal_size         1.0.0                h38e98db_0  
gevent                    20.6.2           py37he774522_0  
glob2                     0.7                        py_0  
glue-core                 0.15.6                   py37_0  
glue-vispy-viewers        0.12.2                     py_0  
glueviz                   0.15.2                        0  
greenlet                  0.4.16           py37he774522_0  
h5py                      2.10.0           py37h5e291fa_0  
hdf5                      1.10.4               h7ebc959_0  
heapdict                  1.0.1                      py_0  
html5lib                  1.1                        py_0  
hypothesis                5.29.0                     py_0  
icc_rt                    2019.0.0             h0cc432a_1  
icu                       58.2                 ha925a31_3  
idna                      2.10                       py_0  
imageio                   2.9.0                      py_0  
imagesize                 1.2.0                      py_0  
importlib-metadata        1.7.0                    py37_0  
importlib_metadata        1.7.0                         0  
iniconfig                 1.0.1                      py_0  
intel-openmp              2020.2                      254  
ipykernel                 5.3.4            py37h5ca1d4c_0  
ipyleaflet                0.13.3                   pypi_0    pypi
ipython                   7.18.1           py37h5ca1d4c_0  
ipython_genutils          0.2.0                    py37_0  
ipywidgets                7.5.1                      py_0  
isort                     5.4.2                    py37_0  
itsdangerous              1.1.0                    py37_0  
jdcal                     1.4.1                      py_0  
jedi                      0.13.3                   py37_0  
jellyfish                 0.8.2                    pypi_0    pypi
jinja2                    2.11.2                     py_0  
jinja2-time               0.2.0                    pypi_0    pypi
joblib                    0.16.0                     py_0  
joypy                     0.2.2                    pypi_0    pypi
jpeg                      9b                   hb83a4c4_2  
json5                     0.9.5                      py_0  
jsonschema                3.2.0                    py37_1  
jupyter                   1.0.0                    py37_7  
jupyter_client            6.1.6                      py_0  
jupyter_console           6.2.0                      py_0  
jupyter_core              4.6.3                    py37_0  
jupyterlab                2.2.6                      py_0  
jupyterlab-black          0.2.1                    pypi_0    pypi
jupyterlab_server         1.2.0                      py_0  
keyring                   21.4.0                   py37_0  
kiwisolver                1.2.0            py37h74a9793_0  
krb5                      1.18.2               hc04afaa_0  
lazy-object-proxy         1.4.3            py37he774522_0  
libarchive                3.4.2                h5e25573_0  
libcurl                   7.71.1               h2a8f88b_1  
libiconv                  1.15                 h1df5818_7  
liblief                   0.10.1               ha925a31_0  
libllvm9                  9.0.1                h21ff451_0  
libpng                    1.6.37               h2a8f88b_0  
libsodium                 1.0.18               h62dcd97_0  
libssh2                   1.9.0                h7a1dbc1_1  
libtiff                   4.1.0                h56a325e_1  
libxml2                   2.9.10               h464c3ec_1  
libxslt                   1.1.34               he774522_0  
lime                      0.2.0.1                  pypi_0    pypi
llvmlite                  0.33.0           py37ha925a31_0  
locket                    0.2.0                    py37_1  
lxml                      4.5.2            py37h1350720_0  
lz4-c                     1.9.2                h62dcd97_1  
lzo                       2.10                 he774522_2  
m2w64-gcc-libgfortran     5.3.0                         6  
m2w64-gcc-libs            5.3.0                         7  
m2w64-gcc-libs-core       5.3.0                         7  
m2w64-gmp                 6.1.0                         2  
m2w64-libwinpthread-git   5.0.0.4634.697f757               2  
markdown                  3.1.1                    pypi_0    pypi
markupsafe                1.1.1            py37hfa6e2cd_1  
matplotlib                3.3.1                         0  
matplotlib-base           3.3.1            py37hba9282a_0  
mccabe                    0.6.1                    py37_1  
menuinst                  1.4.16           py37he774522_0  
mistune                   0.8.4           py37hfa6e2cd_1001  
mkl                       2020.2                      256  
mkl-service               2.3.0            py37hb782905_0  
mkl_fft                   1.1.0            py37h45dec08_0  
mkl_random                1.1.1            py37h47e9c7a_0  
mock                      4.0.2                      py_0  
more-itertools            8.5.0                      py_0  
mpl-scatter-density       0.7                        py_0  
mpmath                    1.1.0                    py37_0  
msgpack-python            1.0.0            py37h74a9793_1  
msys2-conda-epoch         20160418                      1  
multipledispatch          0.6.0                    py37_0  
navigator-updater         0.2.1                    py37_0  
nb-black                  1.0.6                    pypi_0    pypi
nbconvert                 5.6.1                    py37_1  
nbformat                  5.0.7                      py_0  
networkx                  2.5                        py_0  
nltk                      3.5                        py_0  
nose                      1.3.7                 py37_1004  
notebook                  6.1.1                    py37_0  
numba                     0.50.1           py37h47e9c7a_0  
numexpr                   2.7.1            py37h25d0782_0  
numpy                     1.19.1           py37h5510c5b_0  
numpy-base                1.19.1           py37ha3acd2a_0  
numpydoc                  1.1.0                      py_0  
olefile                   0.46                     py37_0  
openpyxl                  3.0.5                      py_0  
openssl                   1.1.1g               he774522_1  
packaging                 20.4                       py_0  
pandas                    1.1.1            py37ha925a31_0  
pandoc                    2.10.1                        0  
pandocfilters             1.4.2                    py37_1  
panel                     0.6.2                    pypi_0    pypi
param                     1.9.1                    pypi_0    pypi
parso                     0.8.0                      py_0  
partd                     1.1.0                      py_0  
path                      15.0.0                   py37_0  
path.py                   12.5.0                        0  
pathlib2                  2.3.5                    py37_1  
patsy                     0.5.1                    py37_0  
pep8                      1.7.1                    py37_0  
pickleshare               0.7.5                 py37_1001  
pillow                    7.2.0            py37hcc1f983_0  
pip                       20.2.2                   py37_0  
pkginfo                   1.5.0.1                  py37_0  
plotly                    4.10.0                     py_0  
pluggy                    0.13.1                   py37_0  
ply                       3.11                     py37_0  
pooch                     1.2.0                    pypi_0    pypi
powershell_shortcut       0.0.1                         2  
poyo                      0.5.0                    pypi_0    pypi
prometheus_client         0.8.0                      py_0  
prompt-toolkit            3.0.7                      py_0  
prompt_toolkit            3.0.7                         0  
properties                0.5.6                    pypi_0    pypi
psutil                    5.7.2            py37he774522_0  
pvgeo                     2.0.4                    pypi_0    pypi
py                        1.9.0                      py_0  
py-lief                   0.10.1           py37ha925a31_0  
pycodestyle               2.6.0                      py_0  
pycosat                   0.6.3            py37he774522_0  
pycparser                 2.20                       py_2  
pycrypto                  2.6.1           py37he774522_10  
pyct                      0.4.6                    pypi_0    pypi
pycurl                    7.43.0.5         py37h7a1dbc1_0  
pydot                     1.4.1                    pypi_0    pypi
pydotplus                 2.0.2                    pypi_0    pypi
pyflakes                  2.2.0                      py_0  
pygments                  2.6.1                      py_0  
pylint                    2.6.0                    py37_0  
pyodbc                    4.0.30           py37ha925a31_0  
pyopengl                  3.1.1a1                  py37_0  
pyopenssl                 19.1.0                     py_1  
pyparsing                 2.4.7                      py_0  
pyqt                      5.9.2            py37h6538335_2  
pyreadline                2.1                      py37_1  
pyrsistent                0.16.0           py37he774522_0  
pysocks                   1.7.1                    py37_1  
pytables                  3.6.1            py37h1da0976_0  
pytest                    6.0.1                    py37_0  
pytest-arraydiff          0.3              py37h39e3cac_0  
pytest-astropy            0.8.0                      py_0  
pytest-astropy-header     0.1.2                      py_0  
pytest-doctestplus        0.8.0                      py_0  
pytest-openfiles          0.5.0                      py_0  
pytest-remotedata         0.3.2                    py37_0  
python                    3.7.3                h8c8aaf0_1  
python-dateutil           2.8.1                      py_0  
python-graphviz           0.13.2                   pypi_0    pypi
python-libarchive-c       2.9                        py_0  
pytz                      2020.1                     py_0  
pyvista                   0.22.1                   pypi_0    pypi
pyviz-comms               0.7.2                    pypi_0    pypi
pywavelets                1.1.1            py37he774522_0  
pywin32                   227              py37he774522_1  
pywin32-ctypes            0.2.0                 py37_1001  
pywinpty                  0.5.7                    py37_0  
pyyaml                    5.3.1            py37he774522_1  
pyzmq                     19.0.1           py37ha925a31_1  
qt                        5.9.7            vc14h73c81de_0  
qtawesome                 0.7.2                      py_0  
qtconsole                 4.7.6                      py_0  
qtpy                      1.9.0                      py_0  
regex                     2020.7.14        py37he774522_0  
requests                  2.24.0                     py_0  
retrying                  1.3.3                    py37_2  
rope                      0.17.0                     py_0  
ruamel_yaml               0.15.87          py37he774522_1  
scikit-image              0.16.2           py37h47e9c7a_0  
scikit-learn              0.23.2           py37h47e9c7a_0  
scipy                     1.5.2            py37h9439919_0  
scooby                    0.4.3                    pypi_0    pypi
seaborn                   0.10.1                     py_0  
send2trash                1.5.0                    py37_0  
setuptools                49.6.0                   py37_0  
shap                      0.36.0                   pypi_0    pypi
simplegeneric             0.8.1                    py37_2  
singledispatch            3.4.0.3               py37_1000  
sip                       4.19.8           py37h6538335_0  
six                       1.15.0                     py_0  
slicer                    0.0.3                    pypi_0    pypi
snappy                    1.1.8                h33f27b4_0  
snowballstemmer           2.0.0                      py_0  
sortedcollections         1.2.1                      py_0  
sortedcontainers          2.2.2                      py_0  
soupsieve                 2.0.1                      py_0  
sphinx                    3.2.1                      py_0  
sphinxcontrib             1.0                      py37_1  
sphinxcontrib-applehelp   1.0.2                      py_0  
sphinxcontrib-devhelp     1.0.2                      py_0  
sphinxcontrib-htmlhelp    1.0.3                      py_0  
sphinxcontrib-jsmath      1.0.1                      py_0  
sphinxcontrib-qthelp      1.0.3                      py_0  
sphinxcontrib-serializinghtml 1.1.4                      py_0  
sphinxcontrib-websupport  1.2.4                      py_0  
spyder                    3.3.6                    py37_0  
spyder-kernels            0.5.1                    py37_0  
sqlalchemy                1.3.19           py37he774522_0  
sqlite                    3.33.0               h2a8f88b_0  
statsmodels               0.11.1           py37he774522_0  
sympy                     1.6.2                    py37_0  
tbb                       2020.2               h74a9793_0  
tblib                     1.7.0                      py_0  
terminado                 0.8.3                    py37_0  
testpath                  0.4.4                      py_0  
threadpoolctl             2.1.0              pyh5ca1d4c_0  
tk                        8.6.10               he774522_0  
toml                      0.10.1                     py_0  
toolz                     0.10.0                     py_0  
tornado                   6.0.4            py37he774522_1  
tqdm                      4.48.2                     py_0  
traitlets                 4.3.3                    py37_0  
traittypes                0.2.1                    pypi_0    pypi
typed-ast                 1.4.1            py37he774522_0  
typing_extensions         3.7.4.3                    py_0  
unicodecsv                0.14.1                   py37_0  
urllib3                   1.25.10                    py_0  
vc                        14.1                 h0510ff6_4  
vectormath                0.2.2                    pypi_0    pypi
verde                     1.5.0                    pypi_0    pypi
vs2015_runtime            14.16.27012          hf0eaf9b_3  
vtk                       8.1.2                    pypi_0    pypi
wcwidth                   0.2.5                      py_0  
webencodings              0.5.1                    py37_1  
wellpathpy                0.1.0a2                  pypi_0    pypi
werkzeug                  1.0.1                      py_0  
wheel                     0.35.1                     py_0  
whichcraft                0.6.1                    pypi_0    pypi
widgetsnbextension        3.5.1                    py37_0  
win_inet_pton             1.1.0                    py37_0  
win_unicode_console       0.5                      py37_0  
wincertstore              0.2                      py37_0  
winpty                    0.4.3                         4  
wrapt                     1.11.2           py37he774522_0  
xarray                    0.16.0                   pypi_0    pypi
xlrd                      1.2.0                    py37_0  
xlsxwriter                1.3.3                      py_0  
xlwings                   0.20.5                   py37_0  
xlwt                      1.3.0                    py37_0  
xmltodict                 0.12.0                     py_0  
xz                        5.2.5                h62dcd97_0  
yaml                      0.2.5                he774522_0  
zeromq                    4.3.2                ha925a31_3  
zict                      2.0.0                      py_0  
zipp                      3.1.0                      py_0  
zlib                      1.2.11               h62dcd97_4  
zope                      1.0                      py37_1  
zope.event                4.4                      py37_0  
zope.interface            5.1.0            py37he774522_0  
zstd                      1.4.5                h04227a9_0  
</pre>
</details>

**Comment by ahartikainen** [comment]
You are using the base conda env?

Can you test this same with a new conda environment?

Also, what if you manually activate the base

    conda activate base

and then try again.

**Comment by jessepisel** [comment]
It was in the base conda env. In a new anaconda 3.7.3 environment it installed and there is no error on import. Looks like it installed `appdirs 1.4.4` on the install in the new environment. 

Manually activating the base environment had no change, must be with my base anaconda install. On the base install it is `appdirs 1.4.3`, but everything else looks pretty similar to the environment install.

**Comment by leouieda** [comment]
That's very strange since pooch depends on appdirs so it should be pulled in when installing. This sounds more like a conda/Anaconda problem, particularly since it installed correctly in a separate environment. 

Does it work in your base environment if you explicitly `conda in install appdirs`?

**Comment by jessepisel** [comment]
I had no issues with an explicit install of appdirs on the base environment. I agree, I imagine this is a conda/Anaconda issue with adding it to the base env.

**Comment by leouieda** [comment]
Alright, I guess I'll close this since it seems to be resolved. Feel free to reopen if there is anything else 🙂
