### ISSUE TITLE
Fix typos on docstrings

### ISSUE THREAD

**Issue by santisoler** [fatiando/verde#287]
**Description of the desired feature**

Fix typos on `distances.py` and `model_selection.py`:

https://github.com/fatiando/verde/blob/8302ca390658d7212fd5c527feeae23365c58948/verde/distances.py#L18

https://github.com/fatiando/verde/blob/8302ca390658d7212fd5c527feeae23365c58948/verde/model_selection.py#L89

**Comment by coldkillerr** [comment]
> **Description of the desired feature**
> 
> Fix typos on `distances.py` and `model_selection.py`:
> 
> https://github.com/fatiando/verde/blob/8302ca390658d7212fd5c527feeae23365c58948/verde/distances.py#L18
> 
> https://github.com/fatiando/verde/blob/8302ca390658d7212fd5c527feeae23365c58948/verde/model_selection.py#L89

Hey! If nobody is assigned this I can do this

**Comment by santisoler** [comment]
Hi @coldkillerr. Thanks for offering your help, it's much appreciated!
This issue was already taken by @jcrawford on #288.
But feel free to navigate through the Issues of any Fatiando library and find anyone that you might want to tackle.
Thanks again for reaching out!
