### ISSUE TITLE
crs problem

### ISSUE THREAD

**Issue by jaimebayes** [fatiando/verde#325]
Hi, 

I am having problems with verde on Colab, when I run the examples, the notebooks crashes and give me a warning related with restarting the notebook.
When I eliminate (or commenting out), the code below, it runs well, but not showing vectorized data over the grid.
Thank in advance, JL

```
ax = plt.axes(projection=ccrs.Mercator())  # crashes
ax = plt.axes()  # runs ok

transform=ccrs.PlateCarree(),  # crashes
#transform=ccrs.PlateCarree()  # runs ok

Error message:
```
The system detects a fault. You must restart again.
```

**System information**

* Operating system: Colab 
* Python installation (Anaconda, system, ETS): 3
* Version of Python: 3.7
* Version of this package: 1.6.1
* If using conda, paste the output of `conda list` below:

<details>
<summary>output of conda list</summary>
<pre>

PASTE OUTPUT OF CONDA LIST HERE

</pre>
</details>

**Comment by santisoler** [comment]
Hi @jaimebayes! Thanks for opening this issue.

The problem you're facing is not specifically related with Verde itself, but with Cartopy.
The `ccrs` variable stands for the `cartopy.crs` module. It seems that Google Colab is having some problem plotting with Cartopy.
Although we use it on the example gallery, Cartopy is not an easy package to work with, it's hard to install sometimes (specially for its dependencies) and different versions have some known issues.

Would you like to copy and paste the error message you obtain? It would be the text that comes after `Error message:`.

By commenting out the `ccrs` related lines you are trying to generate the plot with `matplotlib` only, without using `cartopy`. That's the fastest workaround: use plain `matplotlib.pyplot` to plot. The problem with this solution is if you plot a grid in geographic coordinates, you won't be projecting, the plot axes will be equispaced scales in degrees.
If you want to go this way, remove the `projection=ccrs.Mercator()` argument from `plt.axes()` and the `transform` arguments on each plot line.

**Comment by jaimebayes** [comment]
Hi Santi, 

Sadly, I got no error message, just this warning "The notebook crashed, you must start again". Nothing else. You are right, Cartopy usually comes with some troubles. I will keep trying to overcome this issue, nothing urgent, but I dont like to left this unsolved. 

Best regards, JL 



> Hi @jaimebayes! Thanks for opening this issue.
> 
> The problem you're facing is not specifically related with Verde itself, but with Cartopy.
> The `ccrs` variable stands for the `cartopy.crs` module. It seems that Google Colab is having some problem plotting with Cartopy.
> Although we use it on the example gallery, Cartopy is not an easy package to work with, it's hard to install sometimes (specially for its dependencies) and different versions have some known issues.
> 
> Would you like to copy and paste the error message you obtain? It would be the text that comes after `Error message:`.
> 
> By commenting out the `ccrs` related lines you are trying to generate the plot with `matplotlib` only, without using `cartopy`. That's the fastest workaround: use plain `matplotlib.pyplot` to plot. The problem with this solution is if you plot a grid in geographic coordinates, you won't be projecting, the plot axes will be equispaced scales in degrees.
> If you want to go this way, remove the `projection=ccrs.Mercator()` argument from `plt.axes()` and the `transform` arguments on each plot line.

**Comment by leouieda** [comment]
Hi @jaimebayes this is a pretty common problem with Cartopy. Particularly when not using conda. There is a fairly deep rabbit hole to go down starting from here https://stackoverflow.com/questions/60342880/using-cartopy-on-google-colab-crashes-every-time

Closing this issue since it's not a problem with Verde.
