### ISSUE TITLE
Increase the usage of augmented assignment statements

### ISSUE THREAD

**Issue by elfring** [fatiando/verde#332]
:eyes: Some source code analysis tools can help to find opportunities for improving software components.
:thought_balloon: I propose to [increase the usage of augmented assignment statements](https://docs.python.org/3/reference/simple_stmts.html#augmented-assignment-statements "Augmented assignment statements") accordingly.

```diff
diff --git a/verde/coordinates.py b/verde/coordinates.py
index 07fca69..58040fc 100644
--- a/verde/coordinates.py
+++ b/verde/coordinates.py
@@ -1308,8 +1308,8 @@ def longitude_continuity(coordinates, region):
     all_globe = np.allclose(abs(e - w), 360)
     # Move coordinates to [0, 360)
     interval_360 = True
-    w = w % 360
-    e = e % 360
+    w %= 360
+    e %= 360
     # Move west=0 and east=360 if region longitudes goes all around the globe
     if all_globe:
         w, e = 0, 360
@@ -1326,7 +1326,7 @@ def longitude_continuity(coordinates, region):
         _check_geographic_coordinates(coordinates)
         longitude = coordinates[0]
         if interval_360:
-            longitude = longitude % 360
+            longitude %= 360
         else:
             longitude = ((longitude + 180) % 360) - 180
         coordinates = np.array(coordinates)
```

**Comment by leouieda** [comment]
Thanks for the issue @elfring and sorry that it hung around for so long. We use this very infrequently and it's only for scalar variables so there is no performance impact. So it doesn't seem worth the effort to change these for the sake of changing.

Again, thank you for reporting!

**Comment by elfring** [comment]
I find that [the rationale of the Python enhancement proposal 203](https://www.python.org/dev/peps/pep-0203/#rationale "Proposal for augmented assignments") (from 2000-07-13) can indicate also motivation for another bit of collateral evolution. :thinking:
