### ISSUE TITLE
Function to compute the FFT of xarray grids

### ISSUE THREAD

**Issue by leouieda** [fatiando/verde#36]
Verde uses `xarray.DataArrays` to represent a gridded variable. It conveniently wraps the values and coordinates. We need a function `fft_grid(grid) -> grid_fft` that takes an xarray grid as input and outputs another xarray grid with the complex Fourier transform of the grid data. The coordinates should be wavenumbers in the increasing values (`fftshift`ed).

This is a requirement for #8 and for radial averaged power spectrum.

**Comment by rabernat** [comment]
I recently learned about this very cool package and was browsing your repo.

You might be interested in our package xrft: https://xrft.readthedocs.io/en/latest/
"xrft is a Python package for taking the discrete Fourier transform (DFT) on xarray and dask arrays."

It does exactly what you are looking for.

**Comment by leouieda** [comment]
Wow I missed that somehow. Thanks! One less thing to implement and maintain :)
