### ISSUE TITLE
Function to compute finite-difference derivatives of grids

### ISSUE THREAD

**Issue by leouieda** [fatiando/verde#37]
We need a function to calculate a finite-difference gradient of a xarray.DataArray. The function should look like  `gradientfd(grid, azimuth) -> gradient_grid` that takes in a DataArray and direction (azimuth) and calculates the gradient in that direction using central differences. The boundary conditions should be that the second derivative is zero (i.e., copy the derivative values to the borders). 

East and North derivatives can be calculated easily using azimuths 90 and 0. 

This will complement #8 but has less prerequisites for getting started (no FFT or padding required).

**Comment by rabernat** [comment]
I recently learned about your package and was browsing your repository. It's a great piece of work!

I have developed xgcm for for doing this sort of thing on GCM grids:
https://xgcm.readthedocs.io/en/latest/

It may have some use in your project.
