### ISSUE TITLE
Interactive examples for verde

### ISSUE THREAD

**Issue by edublancas** [fatiando/verde#414]
Hi verde team!

My team maintains a few [open-source](https://github.com/ploomber/jupysql) projects, and we've seen that having interactive examples greatly helps newcomers! We're maintaining a Binder cluster that provides ephemeral JupyterLab sessions ([example](https://binder.ploomber.io/v2/gh/ploomber/jupysql/master?urlpath=lab/tree/doc/quick-start.md)). It essentially spins up a JupyterLab session with pre-made examples.

We're happy to sponsor verde with some computing power. If you're interested, please get in touch with me! (my contact info is in my [profile](https://github.com/edublancas/))

**Comment by leouieda** [comment]
Thank you for the generous offer @edublancas! Unfortunately, we'll have to decline at this point. We're a small team and have trouble keeping up with all of the platforms we currently use already. Great work, by the way!

**Comment by edublancas** [comment]
no problem! thanks for your consideration!
